name: ksquare_challenge
description: "Challenge app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  injectable: ^2.5.0
  internet_connection_checker_plus: ^2.7.0
  flutter_bloc: ^9.0.0
  flutter_gen: ^5.9.0
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^14.8.0
  safe_extensions: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  flutter_gen_runner: ^5.9.0
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter_gen:
  output: lib/src/core/shared/gen
  assets:
    outputs:
      package_parameter_enabled: false
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
